spring:
  datasource:
    url: jdbc:mysql://192.168.1.154:3306/activiti?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 10
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml,classpath:mapper/*.xml
  type-aliases-package: com.example.springbootmybatis.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    capital-mode: true
    #刷新mapper 调试神器
    refresh-mapper: true
  # 打印sql语句,调试用
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
    #mybatis二级缓存
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


